In [1]:
from hello_agents.context import ContextBuilder, ContextConfig
from hello_agents.tools import MemoryTool, RAGTool
from hello_agents.core.message import Message
from datetime import datetime

# 1. 初始化工具
memory_tool = MemoryTool(user_id="user123")
rag_tool = RAGTool(knowledge_base_path="./knowledge_base")

# 2. 创建 ContextBuilder
config = ContextConfig(
    max_tokens=3000,
    reserve_ratio=0.2,
    min_relevance=0.2,
    enable_compression=True
)

builder = ContextBuilder(
    memory_tool=memory_tool,
    rag_tool=rag_tool,
    config=config
)

# 3. 准备对话历史
conversation_history = [
    Message(content="我正在开发一个数据分析工具", role="user", timestamp=datetime.now()),
    Message(content="很好!数据分析工具通常需要处理大量数据。您计划使用什么技术栈?", role="assistant", timestamp=datetime.now()),
    Message(content="我打算使用Python和Pandas,已经完成了CSV读取模块", role="user", timestamp=datetime.now()),
    Message(content="不错的选择!Pandas在数据处理方面非常强大。接下来您可能需要考虑数据清洗和转换。", role="assistant", timestamp=datetime.now()),
]

[OK] SQLite 数据库表和索引创建完成
[OK] SQLite 文档存储初始化完成: ./memory_data/memory.db


INFO:datasets:PyTorch version 2.7.0 available.
INFO:sentence_transformers.SentenceTransformer:Use pytorch device_name: cuda:0
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: sentence-transformers/all-MiniLM-L6-v2


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:hello_agents.memory.storage.qdrant_store:✅ 成功连接到Qdrant云服务: https://5fcb9a5f-5f5d-4594-be66-8245dd4054ee.us-east4-0.gcp.cloud.qdrant.io:6333
INFO:hello_agents.memory.storage.qdrant_store:✅ 使用现有Qdrant集合: hello_agents_vectors


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:hello_agents.memory.types.semantic:✅ 嵌入模型就绪，维度: 384
INFO:hello_agents.memory.types.semantic:✅ Qdrant向量数据库初始化完成
INFO:hello_agents.memory.storage.neo4j_store:✅ 成功连接到Neo4j云服务: neo4j+s://7f7126bb.databases.neo4j.io
INFO:hello_agents.memory.storage.neo4j_store:✅ Neo4j索引创建完成
INFO:hello_agents.memory.types.semantic:✅ Neo4j图数据库初始化完成
INFO:hello_agents.memory.types.semantic:🏥 数据库健康状态: Qdrant=✅, Neo4j=✅
INFO:hello_agents.memory.types.semantic:✅ 加载中文spaCy模型: zh_core_web_sm
INFO:hello_agents.memory.types.semantic:✅ 加载英文spaCy模型: en_core_web_sm
INFO:hello_agents.memory.types.semantic:🎯 主要使用中文spaCy模型
INFO:hello_agents.memory.types.semantic:📚 可用语言模型: 中文, 英文
INFO:hello_agents.memory.types.semantic:增强语义记忆初始化完成（使用Qdrant+Neo4j专业数据库）
INFO:hello_agents.memory.manager:MemoryManager初始化完成，启用记忆类型: ['working', 'episodic', 'semantic']
INFO:hello_agents.memory.storage.qdrant_store:✅ 成功连接到Qdrant云服务: https://5fcb9a5f-5f5d-4594-be66-8245dd4054ee.us-east4-0.gcp.cloud.qdrant.io:6333
INFO:hello_agents.memory.storage

✅ RAG工具初始化成功: namespace=default, collection=rag_knowledge_base


In [2]:
# 4. 添加一些记忆
memory_tool.execute(
    "add",
    content="用户正在开发数据分析工具,使用Python和Pandas",
    memory_type="semantic",
    importance=0.8
)

memory_tool.execute(
    "add",
    content="已完成CSV读取模块的开发",
    memory_type="episodic",
    importance=0.7
)

# 5. 构建上下文
context = builder.build(
    user_query="如何优化Pandas的内存占用?",
    conversation_history=conversation_history,
    system_instructions="你是一位资深的Python数据工程顾问。你的回答需要:1) 提供具体可行的建议 2) 解释技术原理 3) 给出代码示例"
)

print("=" * 80)
print("构建的上下文:")
print("=" * 80)
print(context)
print("=" * 80)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:hello_agents.memory.storage.qdrant_store:[Qdrant] add_vectors start: n_vectors=1 n_meta=1 collection=hello_agents_vectors
INFO:hello_agents.memory.storage.qdrant_store:[Qdrant] upsert begin: points=1
INFO:hello_agents.memory.storage.qdrant_store:[Qdrant] upsert done
INFO:hello_agents.memory.storage.qdrant_store:✅ 成功添加 1 个向量到Qdrant
INFO:hello_agents.memory.types.semantic:✅ 添加语义记忆: 0个实体, 0个关系


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:hello_agents.memory.storage.qdrant_store:[Qdrant] add_vectors start: n_vectors=1 n_meta=1 collection=hello_agents_vectors
INFO:hello_agents.memory.storage.qdrant_store:[Qdrant] upsert begin: points=1
INFO:hello_agents.memory.storage.qdrant_store:[Qdrant] upsert done
INFO:hello_agents.memory.storage.qdrant_store:✅ 成功添加 1 个向量到Qdrant


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:hello_agents.memory.types.semantic:✅ 检索到 1 条相关记忆


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:hello_agents.memory.types.semantic:✅ 检索到 1 条相关记忆


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

构建的上下文:
[Role & Policies]
你是一位资深的Python数据工程顾问。你的回答需要:1) 提供具体可行的建议 2) 解释技术原理 3) 给出代码示例

[Task]
用户问题：如何优化Pandas的内存占用?

[Output]
                            请按以下格式回答：
                            1. 结论（简洁明确）
                            2. 依据（列出支撑证据及来源）
                            3. 风险与假设（如有）
                            4. 下一步行动建议（如适用）


In [3]:
from hello_agents import SimpleAgent, HelloAgentsLLM, ToolRegistry
from hello_agents.context import ContextBuilder, ContextConfig
from hello_agents.tools import MemoryTool, RAGTool

class ContextAwareAgent(SimpleAgent):
    """具有上下文感知能力的 Agent"""

    def __init__(self, name: str, llm: HelloAgentsLLM, **kwargs):
        super().__init__(name=name, llm=llm, system_prompt=kwargs.get("system_prompt", ""))

        # 初始化上下文构建器
        self.memory_tool = MemoryTool(user_id=kwargs.get("user_id", "default"))
        self.rag_tool = RAGTool(knowledge_base_path=kwargs.get("knowledge_base_path", "./kb"))

        self.context_builder = ContextBuilder(
            memory_tool=self.memory_tool,
            rag_tool=self.rag_tool,
            config=ContextConfig(max_tokens=4000)
        )

        self.conversation_history = []

    def run(self, user_input: str) -> str:
        """运行 Agent,自动构建优化的上下文"""

        # 1. 使用 ContextBuilder 构建优化的上下文
        optimized_context = self.context_builder.build(
            user_query=user_input,
            conversation_history=self.conversation_history,
            system_instructions=self.system_prompt
        )

        # 2. 使用优化后的上下文调用 LLM
        messages = [
            {"role": "system", "content": optimized_context},
            {"role": "user", "content": user_input}
        ]
        response = self.llm.invoke(messages)

        # 3. 更新对话历史
        from hello_agents.core.message import Message
        from datetime import datetime

        self.conversation_history.append(
            Message(content=user_input, role="user", timestamp=datetime.now())
        )
        self.conversation_history.append(
            Message(content=response, role="assistant", timestamp=datetime.now())
        )

        # 4. 将重要交互记录到记忆系统
        self.memory_tool.execute(
            "add",
            content=f"Q: {user_input}\nA: {response[:200]}...",  # 摘要
            memory_type="episodic",
            importance=0.6
        )

        return response


In [ ]:
# 使用示例
agent = ContextAwareAgent(
    name="数据分析顾问",
    llm=HelloAgentsLLM(),
    system_prompt="你是一位资深的Python数据工程顾问。",
    user_id="user123",
    knowledge_base_path="./data_science_kb"
)

response = agent.run("如何优化Pandas的内存占用?")
print(response)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:hello_agents.memory.types.semantic:✅ 嵌入模型就绪，维度: 384
INFO:hello_agents.memory.types.semantic:✅ Qdrant向量数据库初始化完成
INFO:hello_agents.memory.storage.neo4j_store:✅ 成功连接到Neo4j云服务: neo4j+s://7f7126bb.databases.neo4j.io
INFO:hello_agents.memory.storage.neo4j_store:✅ Neo4j索引创建完成
INFO:hello_agents.memory.types.semantic:✅ Neo4j图数据库初始化完成
INFO:hello_agents.memory.types.semantic:🏥 数据库健康状态: Qdrant=✅, Neo4j=✅
INFO:hello_agents.memory.types.semantic:✅ 加载中文spaCy模型: zh_core_web_sm
INFO:hello_agents.memory.types.semantic:✅ 加载英文spaCy模型: en_core_web_sm
INFO:hello_agents.memory.types.semantic:🎯 主要使用中文spaCy模型
INFO:hello_agents.memory.types.semantic:📚 可用语言模型: 中文, 英文
INFO:hello_agents.memory.types.semantic:增强语义记忆初始化完成（使用Qdrant+Neo4j专业数据库）
INFO:hello_agents.memory.manager:MemoryManager初始化完成，启用记忆类型: ['working', 'episodic', 'semantic']
INFO:hello_agents.memory.storage.qdrant_store:✅ 成功连接到Qdrant云服务: https://5fcb9a5f-5f5d-4594-be66-8245dd4054ee.us-east4-0.gcp.cloud.qdrant.io:6333
INFO:hello_agents.memory.storage

✅ RAG工具初始化成功: namespace=default, collection=rag_knowledge_base


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:hello_agents.memory.types.semantic:✅ 检索到 1 条相关记忆


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:hello_agents.memory.types.semantic:✅ 检索到 1 条相关记忆


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:hello_agents.memory.storage.qdrant_store:[Qdrant] add_vectors start: n_vectors=1 n_meta=1 collection=hello_agents_vectors
INFO:hello_agents.memory.storage.qdrant_store:[Qdrant] upsert begin: points=1
INFO:hello_agents.memory.storage.qdrant_store:[Qdrant] upsert done
INFO:hello_agents.memory.storage.qdrant_store:✅ 成功添加 1 个向量到Qdrant


1. **结论**  
优化Pandas的内存占用可以通过以下几种方法：  
   - 减少数据类型的内存占用，例如使用更小的数值类型和分类数据类型。  
   - 按需加载数据，采用分块读取。  
   - 删除不必要的数据列和中间变量。  
   - 使用更高效的数据结构，如`numpy`和`dask`。  

2. **依据**  
   - **减少数据类型的存储空间**：Pandas默认使用较宽泛的数据类型（如`float64`和`int64`），但实际数据可能只需要低精度类型。例如，将`float64`降为`float32`可以减少一半内存占用。对于字符串数据，转换为`category`类型可以显著降低内存需求。  
     - 来源：Pandas官方文档关于`astype`与`category`的使用说明。  
   - **分块读取数据**：对于大文件，使用`pandas.read_csv()`的`chunksize`参数按块读取，避免一次加载全部数据造成内存溢出。  
     - 来源：[官方文档 - pandas.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)  
   - **删除不必要的对象**：及时删除不再使用的DataFrame、Series对象并调用`gc.collect()`释放内存。  
     - 来源：Python GC（垃圾回收）机制。  
   - **使用更高效的数据工具**：在处理超大规模数据时，`numpy`或`dask`等工具比Pandas更加内存友好。Dask DataFrame可以对数据进行分布式处理，按需计算，显著降低单机内存压力。  
     - 来源：[Dask官方文档](https://docs.dask.org/en/stable/)  

3. **风险与假设**  
   - **风险**：  
     - 使用更低精度的数据类型（如将`float64`降为`float32`）可能会导致精度损失。  
     - 转换为`category`类型可能对高基数的文本列效率不高，反而增加时间开销。  
   - **假设**：以上优化假设数据量较大（数百万行及以上），内存不足是实际问题；小

# notetool

In [5]:
from hello_agents.tools import NoteTool

notes = NoteTool(workspace="./project_notes")

note_id = notes.run({
    "action": "create",
    "title": "重构项目 - 第一阶段",
    "content": """## 完成情况
已完成数据模型层的重构,测试覆盖率达到85%。

## 下一步
重构业务逻辑层""",
    "note_type": "task_state",
    "tags": ["refactoring", "phase1"]
})

print(f"✅ 笔记创建成功,ID: {note_id}")


✅ 笔记创建成功,ID: ✅ 笔记创建成功
ID: note_20251205_071349_0
标题: 重构项目 - 第一阶段
类型: task_state


In [16]:
data = [
    {"id": 1, "value": "B"},
    {"id": 2, "value": "D"},
    {"id": 3, "value": "C"},
]

data.sort(key=lambda item: item.get("value"), reverse=False)
data
del data[0]
data

[{'id': 3, 'value': 'C'}, {'id': 2, 'value': 'D'}]

In [17]:
data = {
    "note_001": {
        "title": "重构项目 - 第一阶段",
        "type": "task_state",
        "file_path": "/notes/note_001.md",
        "updated_at": "2025-01-12T10:30:00"
    },
    "note_002": {
        "title": "依赖冲突问题",
        "type": "blocker",
        "file_path": "/notes/note_002.md",
        "updated_at": "2025-01-11T21:00:00"
    }
}

del data["note_002"]["title"]
data

{'note_001': {'title': '重构项目 - 第一阶段',
  'type': 'task_state',
  'file_path': '/notes/note_001.md',
  'updated_at': '2025-01-12T10:30:00'},
 'note_002': {'type': 'blocker',
  'file_path': '/notes/note_002.md',
  'updated_at': '2025-01-11T21:00:00'}}

In [38]:
import pandas as pd
import numpy as np

# 读取 Excel 文件
df = pd.read_excel("/mnt/d/studying-code/Large-Model-Application-Development/hello-agents/chapter9/副本sta-动画流畅与连贯性.xlsx")

# 如果第一列是“序号”，通常不参与矩阵数据，可以删掉
if df.columns[0] in ["序号", "编号", "ID"]:
    df = df.iloc[:, 1:]   # 删除第一列

# 将 dataframe 转换成 numpy 矩阵
matrix = df.to_numpy()

print("矩阵形状（用户数 × 题项数）:", matrix.shape)
print(matrix)

矩阵形状（用户数 × 题项数）: (32, 20)
[[ 1  1  1  1  1  1  1  1  1  1  1  0  1  1  0  1  1  1  1 -1]
 [ 1  0  1  1  1  1  1  1  1  1  1  1  1  0 -1 -1  1  1  1  0]
 [ 1  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 0 -1  0  1  1  0  1 -1 -1  0  1 -1 -1  0 -1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0]
 [ 1  0  0  1  1  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  0  1  1  1  1  1  0  1  0  1  1  1]
 [ 0  1  1  1  1  1  0  1  1  1  1  1 -1  1  0  1  1  1  1  1]
 [ 1  1  1  1  1 -1  1  1  1  1  1  0  1  1  1  1  1  1  1  1]
 [ 1 -1  0  1  0 -1  0 -1  1 -1  1  1  1  0  1  0 -1  1  1 -1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1 -1 -1  1 -1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  0  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  0 

In [37]:
import numpy as np
from scipy import stats

# participants_data = matrix  # 你之前读入的矩阵
participants_data = matrix

# --- 2. Calculate Preference Scores ---
user_scores = []
for p_trials in participants_data:

    # 使用 numpy 统计 1 和 -1 的数量
    wins = np.sum(p_trials == 1)
    losses = np.sum(p_trials == -1)
    total = len(p_trials)

    # Calculate normalized score (-1 to 1)
    score = (wins - losses) / total
    user_scores.append(score)

print(f"User Scores: {user_scores}")

# --- 3. Descriptive Stats (Median & IQR) ---
median = np.median(user_scores)
q75, q25 = np.percentile(user_scores, [75 ,25])
iqr = q75 - q25

print("\n--- Descriptive Statistics ---")
print(f"Median (Mdn): {median:.4f}")
print(f"IQR: {iqr:.4f}")

# --- 4. The Statistical Test (Wilcoxon) ---
w_stat, p_value = stats.wilcoxon(user_scores)

# Approximate Z-score for reporting
z_score = stats.norm.ppf(p_value/2) * -1  # two-tailed

# Effect Size
N = len(user_scores)
r_effect = abs(z_score) / np.sqrt(N)

print("\n--- Inference Statistics ---")
print(f"Wilcoxon Statistic (W): {w_stat:.4f}")
print(f"P-value: {p_value:.5f}")
print(f"Z-score (approx): {z_score:.4f}")
print(f"Effect Size (r): {r_effect:.4f}")


User Scores: [np.float64(0.9), np.float64(0.6), np.float64(0.85), np.float64(0.3), np.float64(0.9), np.float64(0.85), np.float64(0.95), np.float64(0.3), np.float64(0.7), np.float64(0.85), np.float64(0.15), np.float64(0.95), np.float64(0.45), np.float64(0.9), np.float64(0.65), np.float64(0.4), np.float64(0.1), np.float64(0.65), np.float64(0.55), np.float64(0.35), np.float64(1.0), np.float64(0.55), np.float64(0.1), np.float64(0.5), np.float64(0.5), np.float64(0.15), np.float64(0.45), np.float64(0.2), np.float64(0.7), np.float64(0.55), np.float64(0.8), np.float64(0.75)]

--- Descriptive Statistics ---
Median (Mdn): 0.5750
IQR: 0.4625

--- Inference Statistics ---
Wilcoxon Statistic (W): 0.0000
P-value: 0.00000
Z-score (approx): 4.9387
Effect Size (r): 0.8730
